import { prisma } from '@/lib/prisma'
import * as fs from 'fs'

export async function updatePage(input: { pageId: string, blockType: string, data: any }, ctx: { userId: string }) {
  fs.appendFileSync('update-page-debug.log', `\n\n--- updatePage called at ${new Date().toISOString()} ---\nINPUT: ${JSON.stringify(input, null, 2)}\n`);
  console.log("\n[Agent Tools - updatePage] RUNNING WITH INPUT:", JSON.stringify(input, null, 2));
  
  try {
    const page = await prisma.page.findUnique({ where: { id: input.pageId } })
    if (!page || !page.blockJson) {
        console.error("[Agent Tools - updatePage] Page not found or no blockJson. PageId:", input.pageId);
        throw new Error("Page not found")
    }
    
    let currentBlocks = page.blockJson as any[]

    function createBlock(type: string, payload: any) {
      if (type === 'diagram') {
        return { 
          id: `diagram-${Date.now()}-${Math.random()}`, 
          type: "excalidraw", 
          props: { 
            textColor: "default", 
            backgroundColor: "default", 
            textAlignment: "left", 
            appState: "null", 
            mermaidCode: payload.mermaidCode || "",
            elements: payload.elements ? (typeof payload.elements === 'string' ? payload.elements : JSON.stringify(payload.elements)) : "[]", 
            files: payload.files ? (typeof payload.files === 'string' ? payload.files : JSON.stringify(payload.files)) : "null" 
          }, 
          content: [] 
        }
      }
      if (type === 'video') return { id: `video-${Date.now()}-${Math.random()}`, type: "video", props: { url: payload }, content: [] }
      if (type === 'p5') return { id: `p5-${Date.now()}-${Math.random()}`, type: "p5", props: { code: payload }, content: [] }
      if (type === 'desmos') return { id: `desmos-${Date.now()}-${Math.random()}`, type: "desmos", props: { equations: typeof payload === 'string' ? payload : JSON.stringify(payload) }, content: [] }
      if (type === 'text' || type === 'paragraph') {
        return {
          id: `text-${Date.now()}-${Math.random()}`, 
          type: "paragraph", 
          props: { textColor: "default", backgroundColor: "default", textAlignment: "left" }, 
          content: [{ type: "text", text: typeof payload === 'string' ? payload : JSON.stringify(payload), styles: {} }] 
        }
      }
      if (type === 'heading') {
        return {
          id: `heading-${Date.now()}-${Math.random()}`,
          type: "heading",
          props: { level: 1, textColor: "default", backgroundColor: "default", textAlignment: "left" },
          content: [{ type: "text", text: typeof payload === 'string' ? payload : JSON.stringify(payload), styles: {} }] 
        }
      }
      return { id: `generic-${Date.now()}-${Math.random()}`, type: type || "paragraph", props: {}, content: [{ type: "text", text: typeof payload === 'string' ? payload : JSON.stringify(payload), styles: {} }] }
    }

    // Check if data is already an array of BlockNote blocks (often generated by generate_blocks tool)
    // The planner might mistakenly send blockType="text" instead of "blocks"
    if (Array.isArray(input.data) && input.data.length > 0 && input.data[0].type) {
        for (const blockData of input.data) {
            if (!blockData.id) {
                blockData.id = `block-${Date.now()}-${Math.random().toString(36).substring(2, 9)}`
            }
            if (!blockData.props) blockData.props = {} // Ensure props object exists
            currentBlocks.push(blockData)
        }
    } else if (input.blockType === 'blocks' && Array.isArray(input.data)) {
        for (const blockData of input.data) {
            if (!blockData.id) {
                blockData.id = `block-${Date.now()}-${Math.random().toString(36).substring(2, 9)}`
            }
            if (!blockData.props) blockData.props = {} // Ensure props object exists
            currentBlocks.push(blockData)
        }
    } else if (input.blockType === 'multi' && typeof input.data === 'object' && input.data !== null) {
        for (const [key, value] of Object.entries(input.data)) {
            const b = createBlock(key, value)
            if (b) currentBlocks.push(b)
        }
    } else {
        const b = createBlock(input.blockType, input.data)
        if (b) currentBlocks.push(b)
    }

    console.log("[Agent Tools - updatePage] Saving blocks to DB. Length:", currentBlocks.length);
    fs.appendFileSync('update-page-debug.log', `Saving blocks to DB. Length: ${currentBlocks.length}\n`);
    await prisma.page.update({ where: { id: input.pageId }, data: { blockJson: currentBlocks as any } })
    console.log("[Agent Tools - updatePage] Saved successfully to Postgres.");
    fs.appendFileSync('update-page-debug.log', `Saved successfully to Postgres.\n`);

    const syncServerUrl = process.env.NEXT_PUBLIC_SYNC_SERVER_URL || "ws://localhost:3000"
    const broadcastHttpUrl = syncServerUrl.replace("ws://", "http://").replace("wss://", "https://") + "/api/broadcast"
    try {
      await fetch(broadcastHttpUrl, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          pageId: input.pageId,
          event: { type: 'ai-update', userId: ctx.userId, blocks: currentBlocks }
        })
      })
      console.log("[Agent Tools - updatePage] Broadcast sent to sync-server.");
    } catch (err) {
      console.error("[Agent Tools - updatePage] Broadcast failed:", err)
    }
    return currentBlocks
  } catch (err: any) {
    console.error("[Agent Tools - updatePage] CRITICAL ERROR:", err.message);
    fs.appendFileSync('update-page-debug.log', `CRITICAL ERROR: ${err.message}\n${err.stack}\n`);
    throw err;
  }
}

export async function broadcastProgress(pageId: string, results: any) {
  const syncServerUrl = process.env.NEXT_PUBLIC_SYNC_SERVER_URL || "ws://localhost:3000"
  const broadcastHttpUrl = syncServerUrl.replace("ws://", "http://").replace("wss://", "https://") + "/api/broadcast"
  try {
    await fetch(broadcastHttpUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        pageId,
        event: { type: 'tool-progress', results }
      })
    })
  } catch (err) {
    console.error("Tool progress broadcast failed:", err)
  }
}
